### ISSUE TITLE
Changing resolutions?

### ISSUE THREAD

**Issue by rygo6** [keijiro/Rsvfx#10]
Hello I have this working with realsense d410 and I was trying to change the resolution. But can't seem to get any other resolution to work. I tried 1280x720 both at 60 fps and 30 fps which I thought the d410 supported, but that doesn't work. Is it possible to set it to a resolution other than 640x480?

**Comment by keijiro** [comment]
I confirmed that 1280x720@30fps works with my d415. Hint: You also have to change the resolution of Position/Depth render textures.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.

**Comment by rygo6** [comment]
Render texture resolution was the problem. Thank you.
