### ISSUE TITLE
Could this be done with Microsoft Kinect v2? 

### ISSUE THREAD

**Issue by MarlonCreative** [keijiro/Rsvfx#2]

**Comment by keijiro** [comment]
It's technically possible, but I'm not very motivated for some reasons (it's hard to find at store, expensive, too bulky, requires a power brick, causes cable mess, etc.). I'd like to keep this repository focused on RealSense as its name implies (RS-VFX). I'll make another repository when I work on Kinect.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
