### ISSUE TITLE
wiper vfx can not be edited in another project

### ISSUE THREAD

**Issue by fdiba** [keijiro/Rsvfx#23]
Hello, when I try to edit wiper vfx inside another project the effect do not work anymore as soon as I open it. It's not the case for the other vfx (like particle, scanner or simple).

I can edit it in the original project but not in a new one. I get these errors: 

Remove 2 child(ren) that couldnt be deserialized from  of type UnityEditor.VFX.VFXGraph
UnityEditor.VFX.VFXGraph:OnEnable()

Remove 2 child(ren) that couldnt be deserialized from  of type UnityEditor.VFX.VFXGraph
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Any idea to solve the problem ?

**Comment by keijiro** [comment]
I think that's because it uses some custom nodes from the [VfxExtra](https://github.com/keijiro/VfxExtra) project. I don't recommend using it in other projects. It's quite dirty hack so that it will be broken in future versions.

**Comment by fdiba** [comment]
Ok, thank you for the tip. I hope the effect will be reproductible at a certain point without the VfxExtra project.

**Comment by keijiro** [comment]
I'll do when VFX Graph gets a proper way to implement a custom node without a hacky way.
