### ISSUE TITLE
How to solve this problem？

### ISSUE THREAD

**Issue by Cicada3306** [keijiro/Rsvfx#25]
Rethrow as Exception:Couldn't resolve request.

**Comment by keijiro** [comment]
It seems to fail to connect to the RealSense device.

- Which RealSense device model are you using?
- Which platform (Windows/Mac/Linux) are you using?
- Which version of Unity are you using?
- Which scene in this project are you trying?

**Comment by Cicada3306** [comment]
RealSense device：D415
using Windows
using Unity2019.1.8f
trying Simple scene

**Comment by keijiro** [comment]
Thanks for the clarification. Could you check if the official Unity RealSense examples work on it? https://github.com/IntelRealSense/librealsense/releases/download/v2.24.0/Intel.RealSense.unitypackage

**Comment by Cicada3306** [comment]
it also not work, i try Record and Playback still have this problem.

**Comment by keijiro** [comment]
Sure. Then it's supposed that there is a problem with RealSense SDK or your environment/hardware. Please refer to the SDK documentation to solve the problem.

I'm closing this issue now. Please feel free to reopen it if it sill reproduces after solving the problem on the SDK side.

**Comment by Cicada3306** [comment]
ok,thanks
