### ISSUE TITLE
Work with Spout

### ISSUE THREAD

**Issue by Zudva** [keijiro/Rsvfx#27]
Hi! I want use you Asset with KlakSpout. I'm not can use it in this project?

**Comment by keijiro** [comment]
You can.

**Comment by keijiro** [comment]
I'm closing this issue now, but please feel free to reopen for further questions.

**Comment by Zudva** [comment]
Keijiro, i add Spout folder with  to Assets in your RsVFX project and add KlakSpout. Spout script see my Touchdesigner spout out, but Touchdesigner spout in node not see Unity Sender script for Camera in scene.
 Sorry, but im not understand how to correctly launch. In new project all work.
Thank you!

**Comment by keijiro** [comment]
Please note that the camera capture mode in the Spout Sender component doesn't support SRP (LWRP/HDRP). That's why your project doesn't show anything on TouchDesigner side. I'd recommend using the Render Texture mode insted. Please check README of KlakSpout for further details.
