### ISSUE TITLE
External Data Question

### ISSUE THREAD

**Issue by rdmerillat** [keijiro/Rsvfx#35]
I had a question pertaining to external data usage, As long as the format of the data was the same (the point source and color source) would it be possible to stream external data from ROS using something like [ros-sharp](https://github.com/siemens/ros-sharp)? Or it the RealSense too integral to be able to use other data. For reference I'm trying to stream point cloud data from ROS into Unity and display the cloud in AR. I also know this is fairly similar to [this issue](https://github.com/keijiro/Rsvfx/issues/3) so I'm sorry if you are repeating any info here.

**Comment by keijiro** [comment]
Rsvfx is too complicated as a reference for what you're trying to do. Most of the code is just for managing the RealSense device that is not very meaningful for your project.

It might sound strange, but I think Smrvfx is a better example for your project.

https://github.com/keijiro/Smrvfx

It consists of a few scripts and a simple compute shader. It just retrieves data and bakes it into textures.

https://github.com/keijiro/Smrvfx/tree/master/Assets/Smrvfx

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.

**Comment by rdmerillat** [comment]
Thanks for the reply and the advice!
