### ISSUE TITLE
Not seeing anything using playback with .bag files. No D400 connected

### ISSUE THREAD

**Issue by 9-zzz** [keijiro/Rsvfx#37]
I downloaded the project and get no errors, I got some sample .bag files from here: https://github.com/IntelRealSense/librealsense/blob/master/doc/sample-data.md

Is the D400 type camera being connected a requirement even for playback?
Sorry if this is not an issue with the code, maybe I don't have the right kind of .bag files
Or some setting is wrong to show playback, just black screen, no errors.

*just realizing, is the playback only for .bag files created within this projects record function?

**Comment by keijiro** [comment]
This project doesn't support the playback functionality.
