### ISSUE TITLE
Multiple real sense camera 

### ISSUE THREAD

**Issue by antoniohof** [keijiro/Rsvfx#4]
Is it possible to use multiple real sense cameras in this project connected to the same PC?

Thank you

Antonio

**Comment by bryanrtboy** [comment]
I know this is not designed for Mac, but I was able to get all of the example scenes working except for Particles. That seems to be the only example using quad output, but I have not been able to figure out why it's not working. There is no emmision of any particles on Play or in the Editor.

**Comment by keijiro** [comment]
@bryanrtboy Is it related to the topic? ("Multiple real sense camera")

If it's not relevant, please repost it as a new issue.

**Comment by keijiro** [comment]
@antoniohof I only have a single RealSense device so I have never tried it, but I think you can use multiple devices with specifying serial numbers in Rs Device components ("Requested Serial Number" property).

**Comment by antoniohof** [comment]
Thanks!
