### ISSUE TITLE
Reverse movement

### ISSUE THREAD

**Issue by fuzzy-duck** [keijiro/Rsvfx#43]
Is there a way to reverse the movement? i.e. if I walk past the camera left to right it simulates right to left.

**Comment by keijiro** [comment]
There are several ways to do it, but they're not directly relevant to the aim of the project (providing a plugin to connect RealSense and VFX Graph). Please understand that this issue tracker is dedicated to solve the technical issues happened in the project. I'd recommend using the Unity forum or other similar communities to solve general problems/questions about Unity.

I'm closing this issue now. Please feel free to reopen it for further problems.
